name: Scrape
on:
  workflow_dispatch:
  schedule:
    - cron: '10 6 * * *'

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - id: pipenv-install
        name: Install Python dependencies
        run: pipenv sync --dev

      - id: make
        name: Run make command
        run: |
          pipenv run python setup.py install
          pipenv run noaawildfires hms-fires > data/hms-fires.json
          pipenv run noaawildfires hms-smoke > data/hms-smoke.json
        shell: bash

      - name: Datestamp
        run: date > data/timestamp.txt
        shell: bash

      - id: commit
        name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git config pull.rebase false
          git status
          git pull origin $GITHUB_REF
          git add ./data
          git commit -m "Scrape" && git push || true
        shell: bash
